### ISSUE TITLE
What is subscale in FALoss?

### ISSUE THREAD

**Issue by AndyChang666** [Dootmaan/DSRL#10]
Hi, Thanks for sharing the code.
I am curious that how you determine the subscale=0.0625?
And have you trained the model with w_sr=0.1, w_fa=1.0? Because the paper is set to these parameters.

Looking forward to your reply.

**Comment by Dootmaan** [comment]
> Hi, Thanks for sharing the code.
> I am curious that how you determine the subscale=0.0625?
> And have you trained the model with w_sr=0.1, w_fa=1.0? Because the paper is set to these parameters.
> 
> Looking forward to your reply.

Hi there, thank you for your question. In the paper, subscale is set to 0.125 to lower the computational cost, and i set it to 0.0625 because at the very beginning i tried many different kinds of implementations of FA module and some of them is very memory-costing, so i just set subscale lower to make sure all of them can work, and thus they can be compared together. You are encouraged to set this parameter as high as possible, according to the paper.
As to w_sr and w_fa, they are set to 0.5 and 0.5 all along, and i have to admit that it is different from the paper(i never noticed that though. Actually i thought they were set to 0.5 in the paper lol). If you tried this parameter setting please tell me your experiment results, thank you.

**Comment by AndyChang666** [comment]
Got it! Thanks for your reply.
